name: my second workflow | training 

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows you to run this manually for testing

jobs:
  first_job:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create dummy script
        run: |
          echo "echo 'Hello from script22!'" > script22.sh
          echo "Current date: $(date)" > build-output.txt

      - name: List files
        run: ls -ltra

      - name: Run shell script
        run: |
          chmod +x script22.sh
          ./script22.sh
        
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: training-artifact
          path: build-output.txt # Change this to the specific file/folder you want to save

      - name: Checkout repo files
        run: ls -R