name: ETL Pipeline

on: [push]

jobs:
  run-etl-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Libraries
        run: pip install pandas pytest dbt-sqlite


      - name: Execute ETL
        run: python etl.py

      - name: Run Unit Tests
        run: pytest tests.py

      - name: Prepare dbt Schema Directory
        run: mkdir -p dbt_schema

      - name: Run dbt models
        run: dbt run --profiles-dir .