version: 2

models:
  - name: sales_transform  # Must match your .sql filename
    columns:
      - name: order_id
        tests:
          - unique
          - not_null
      - name: total_revenue
        tests:
          - accepted_values:
              values: [0]
              quote: false
              operator: ">=" # Ensures no negative revenue
              